on:
  schedule:
  - cron: '16 19 * * *'
defaults:
  run:
    shell: bash
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need-refresh: ${{ steps.check.outputs.need-refresh }}
    timeout-minutes: 1
    steps:
    - name: Check last activity
      id: check
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_PERSONAL_ACCESS_TOKEN }}
      run: |-
        set -euo pipefail
        UPDATED_AT=$(curl -fsS -H 'Accept: application/vnd.github.v3+json' -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/$GITHUB_REPOSITORY" | jq -r .updated_at)
        THRESHOLD=$(date --date="$UPDATED_AT + 50 days" +%s)
        NOW=$(date +%s)
        if [ "$NOW" -gt "$THRESHOLD" ]; then
        	NEED_REFRESH=yes
        else
        	NEED_REFRESH=no
        fi
        echo "::set-output name=need-refresh::$NEED_REFRESH"
  refresh:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.need-refresh == 'yes'
    timeout-minutes: 1
    steps:
    - name: Refresh repository
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_PERSONAL_ACCESS_TOKEN }}
      run: |-
        set -euo pipefail
        UPDATED_AT=$(curl -fsS -H 'Accept: application/vnd.github.v3+json' -H "Authorization: token ${GITHUB_TOKEN}" -H 'Content-Type: application/json' --data-raw '{"has_wiki":false}' "https://api.github.com/repos/$GITHUB_REPOSITORY" | jq -r .updated_at)
        THRESHOLD=$(date --date="$UPDATED_AT + 3 minutes" +%s)
        NOW=$(date +%s)
        test "$NOW" -lt "$THRESHOLD"
